spring:
  jpa:
    properties:
      hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
      type: trace
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
  file: logs/user-data.log